### YamlMime:ManagedReference
items:
- uid: OpenTl.Schema.Messages.TDhConfig
  commentId: T:OpenTl.Schema.Messages.TDhConfig
  id: TDhConfig
  parent: OpenTl.Schema.Messages
  children:
  - OpenTl.Schema.Messages.TDhConfig.G
  - OpenTl.Schema.Messages.TDhConfig.P
  - OpenTl.Schema.Messages.TDhConfig.Random
  - OpenTl.Schema.Messages.TDhConfig.Version
  langs:
  - csharp
  - vb
  name: TDhConfig
  nameWithType: TDhConfig
  fullName: OpenTl.Schema.Messages.TDhConfig
  type: Class
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Messages/DhConfig/TDhConfig.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: TDhConfig
    path: ../src/OpenTl.Schema/_generated/Messages/DhConfig/TDhConfig.cs
    startLine: 11
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Messages
  syntax:
    content: 'public class TDhConfig : object, IDhConfig, IObject'
    content.vb: >-
      Public Class TDhConfig

          Inherits Object

          Implements IDhConfig, IObject
  inheritance:
  - System.Object
  implements:
  - OpenTl.Schema.Messages.IDhConfig
  - OpenTl.Schema.IObject
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: OpenTl.Schema.Messages.TDhConfig.G
  commentId: P:OpenTl.Schema.Messages.TDhConfig.G
  id: G
  parent: OpenTl.Schema.Messages.TDhConfig
  langs:
  - csharp
  - vb
  name: G
  nameWithType: TDhConfig.G
  fullName: OpenTl.Schema.Messages.TDhConfig.G
  type: Property
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Messages/DhConfig/TDhConfig.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: G
    path: ../src/OpenTl.Schema/_generated/Messages/DhConfig/TDhConfig.cs
    startLine: 14
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Messages
  syntax:
    content: public int G { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property G As Integer
  overload: OpenTl.Schema.Messages.TDhConfig.G*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: OpenTl.Schema.Messages.TDhConfig.P
  commentId: P:OpenTl.Schema.Messages.TDhConfig.P
  id: P
  parent: OpenTl.Schema.Messages.TDhConfig
  langs:
  - csharp
  - vb
  name: P
  nameWithType: TDhConfig.P
  fullName: OpenTl.Schema.Messages.TDhConfig.P
  type: Property
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Messages/DhConfig/TDhConfig.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: P
    path: ../src/OpenTl.Schema/_generated/Messages/DhConfig/TDhConfig.cs
    startLine: 17
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Messages
  syntax:
    content: public byte[] P { get; set; }
    parameters: []
    return:
      type: System.Byte[]
    content.vb: Public Property P As Byte()
  overload: OpenTl.Schema.Messages.TDhConfig.P*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: OpenTl.Schema.Messages.TDhConfig.Version
  commentId: P:OpenTl.Schema.Messages.TDhConfig.Version
  id: Version
  parent: OpenTl.Schema.Messages.TDhConfig
  langs:
  - csharp
  - vb
  name: Version
  nameWithType: TDhConfig.Version
  fullName: OpenTl.Schema.Messages.TDhConfig.Version
  type: Property
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Messages/DhConfig/TDhConfig.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: Version
    path: ../src/OpenTl.Schema/_generated/Messages/DhConfig/TDhConfig.cs
    startLine: 20
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Messages
  syntax:
    content: public int Version { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Version As Integer
  overload: OpenTl.Schema.Messages.TDhConfig.Version*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: OpenTl.Schema.Messages.TDhConfig.Random
  commentId: P:OpenTl.Schema.Messages.TDhConfig.Random
  id: Random
  parent: OpenTl.Schema.Messages.TDhConfig
  langs:
  - csharp
  - vb
  name: Random
  nameWithType: TDhConfig.Random
  fullName: OpenTl.Schema.Messages.TDhConfig.Random
  type: Property
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Messages/DhConfig/TDhConfig.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: Random
    path: ../src/OpenTl.Schema/_generated/Messages/DhConfig/TDhConfig.cs
    startLine: 23
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Messages
  syntax:
    content: public byte[] Random { get; set; }
    parameters: []
    return:
      type: System.Byte[]
    content.vb: Public Property Random As Byte()
  overload: OpenTl.Schema.Messages.TDhConfig.Random*
  implements:
  - OpenTl.Schema.Messages.IDhConfig.Random
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: OpenTl.Schema.Messages
  commentId: N:OpenTl.Schema.Messages
  isExternal: false
  name: OpenTl.Schema.Messages
  nameWithType: OpenTl.Schema.Messages
  fullName: OpenTl.Schema.Messages
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: OpenTl.Schema.Messages.IDhConfig
  commentId: T:OpenTl.Schema.Messages.IDhConfig
  parent: OpenTl.Schema.Messages
  isExternal: false
  name: IDhConfig
  nameWithType: IDhConfig
  fullName: OpenTl.Schema.Messages.IDhConfig
- uid: OpenTl.Schema.IObject
  commentId: T:OpenTl.Schema.IObject
  parent: OpenTl.Schema
  isExternal: false
  name: IObject
  nameWithType: IObject
  fullName: OpenTl.Schema.IObject
- uid: OpenTl.Schema
  commentId: N:OpenTl.Schema
  isExternal: false
  name: OpenTl.Schema
  nameWithType: OpenTl.Schema
  fullName: OpenTl.Schema
- uid: OpenTl.Schema.Messages.TDhConfig.G*
  commentId: Overload:OpenTl.Schema.Messages.TDhConfig.G
  isExternal: false
  name: G
  nameWithType: TDhConfig.G
  fullName: OpenTl.Schema.Messages.TDhConfig.G
- uid: System.Int32
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: OpenTl.Schema.Messages.TDhConfig.P*
  commentId: Overload:OpenTl.Schema.Messages.TDhConfig.P
  isExternal: false
  name: P
  nameWithType: TDhConfig.P
  fullName: OpenTl.Schema.Messages.TDhConfig.P
- uid: System.Byte[]
  name: Byte[]
  nameWithType: Byte[]
  fullName: System.Byte[]
  nameWithType.vb: Byte()
  fullName.vb: System.Byte()
  name.vb: Byte()
  spec.csharp:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
  spec.vb:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: ()
    nameWithType: ()
    fullName: ()
- uid: OpenTl.Schema.Messages.TDhConfig.Version*
  commentId: Overload:OpenTl.Schema.Messages.TDhConfig.Version
  isExternal: false
  name: Version
  nameWithType: TDhConfig.Version
  fullName: OpenTl.Schema.Messages.TDhConfig.Version
- uid: OpenTl.Schema.Messages.TDhConfig.Random*
  commentId: Overload:OpenTl.Schema.Messages.TDhConfig.Random
  isExternal: false
  name: Random
  nameWithType: TDhConfig.Random
  fullName: OpenTl.Schema.Messages.TDhConfig.Random
- uid: OpenTl.Schema.Messages.IDhConfig.Random
  commentId: P:OpenTl.Schema.Messages.IDhConfig.Random
  parent: OpenTl.Schema.Messages.IDhConfig
  isExternal: false
  name: Random
  nameWithType: IDhConfig.Random
  fullName: OpenTl.Schema.Messages.IDhConfig.Random
