### YamlMime:ManagedReference
items:
- uid: OpenTl.Schema.Messages.RequestGetDhConfig
  commentId: T:OpenTl.Schema.Messages.RequestGetDhConfig
  id: RequestGetDhConfig
  parent: OpenTl.Schema.Messages
  children:
  - OpenTl.Schema.Messages.RequestGetDhConfig.RandomLength
  - OpenTl.Schema.Messages.RequestGetDhConfig.Version
  langs:
  - csharp
  - vb
  name: RequestGetDhConfig
  nameWithType: RequestGetDhConfig
  fullName: OpenTl.Schema.Messages.RequestGetDhConfig
  type: Class
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Messages/RequestGetDhConfig.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: RequestGetDhConfig
    path: ../src/OpenTl.Schema/_generated/Messages/RequestGetDhConfig.cs
    startLine: 11
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Messages
  syntax:
    content: 'public class RequestGetDhConfig : object, IRequest<IDhConfig>, IRequest, IObject'
    content.vb: >-
      Public Class RequestGetDhConfig

          Inherits Object

          Implements IRequest(Of IDhConfig), IRequest, IObject
  inheritance:
  - System.Object
  implements:
  - OpenTl.Schema.IRequest{OpenTl.Schema.Messages.IDhConfig}
  - OpenTl.Schema.IRequest
  - OpenTl.Schema.IObject
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: OpenTl.Schema.Messages.RequestGetDhConfig.Version
  commentId: P:OpenTl.Schema.Messages.RequestGetDhConfig.Version
  id: Version
  parent: OpenTl.Schema.Messages.RequestGetDhConfig
  langs:
  - csharp
  - vb
  name: Version
  nameWithType: RequestGetDhConfig.Version
  fullName: OpenTl.Schema.Messages.RequestGetDhConfig.Version
  type: Property
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Messages/RequestGetDhConfig.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: Version
    path: ../src/OpenTl.Schema/_generated/Messages/RequestGetDhConfig.cs
    startLine: 14
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Messages
  syntax:
    content: public int Version { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Version As Integer
  overload: OpenTl.Schema.Messages.RequestGetDhConfig.Version*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: OpenTl.Schema.Messages.RequestGetDhConfig.RandomLength
  commentId: P:OpenTl.Schema.Messages.RequestGetDhConfig.RandomLength
  id: RandomLength
  parent: OpenTl.Schema.Messages.RequestGetDhConfig
  langs:
  - csharp
  - vb
  name: RandomLength
  nameWithType: RequestGetDhConfig.RandomLength
  fullName: OpenTl.Schema.Messages.RequestGetDhConfig.RandomLength
  type: Property
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Messages/RequestGetDhConfig.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: RandomLength
    path: ../src/OpenTl.Schema/_generated/Messages/RequestGetDhConfig.cs
    startLine: 17
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Messages
  syntax:
    content: public int RandomLength { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property RandomLength As Integer
  overload: OpenTl.Schema.Messages.RequestGetDhConfig.RandomLength*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: OpenTl.Schema.Messages
  commentId: N:OpenTl.Schema.Messages
  isExternal: false
  name: OpenTl.Schema.Messages
  nameWithType: OpenTl.Schema.Messages
  fullName: OpenTl.Schema.Messages
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: OpenTl.Schema.IRequest{OpenTl.Schema.Messages.IDhConfig}
  commentId: T:OpenTl.Schema.IRequest{OpenTl.Schema.Messages.IDhConfig}
  parent: OpenTl.Schema
  definition: OpenTl.Schema.IRequest`1
  name: IRequest<IDhConfig>
  nameWithType: IRequest<IDhConfig>
  fullName: OpenTl.Schema.IRequest<OpenTl.Schema.Messages.IDhConfig>
  nameWithType.vb: IRequest(Of IDhConfig)
  fullName.vb: OpenTl.Schema.IRequest(Of OpenTl.Schema.Messages.IDhConfig)
  name.vb: IRequest(Of IDhConfig)
  spec.csharp:
  - uid: OpenTl.Schema.IRequest`1
    name: IRequest
    nameWithType: IRequest
    fullName: OpenTl.Schema.IRequest
  - name: <
    nameWithType: <
    fullName: <
  - uid: OpenTl.Schema.Messages.IDhConfig
    name: IDhConfig
    nameWithType: IDhConfig
    fullName: OpenTl.Schema.Messages.IDhConfig
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: OpenTl.Schema.IRequest`1
    name: IRequest
    nameWithType: IRequest
    fullName: OpenTl.Schema.IRequest
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: OpenTl.Schema.Messages.IDhConfig
    name: IDhConfig
    nameWithType: IDhConfig
    fullName: OpenTl.Schema.Messages.IDhConfig
  - name: )
    nameWithType: )
    fullName: )
- uid: OpenTl.Schema.IRequest
  commentId: T:OpenTl.Schema.IRequest
  parent: OpenTl.Schema
  isExternal: false
  name: IRequest
  nameWithType: IRequest
  fullName: OpenTl.Schema.IRequest
- uid: OpenTl.Schema.IObject
  commentId: T:OpenTl.Schema.IObject
  parent: OpenTl.Schema
  isExternal: false
  name: IObject
  nameWithType: IObject
  fullName: OpenTl.Schema.IObject
- uid: OpenTl.Schema.IRequest`1
  commentId: T:OpenTl.Schema.IRequest`1
  isExternal: false
  name: IRequest<TResult>
  nameWithType: IRequest<TResult>
  fullName: OpenTl.Schema.IRequest<TResult>
  nameWithType.vb: IRequest(Of TResult)
  fullName.vb: OpenTl.Schema.IRequest(Of TResult)
  name.vb: IRequest(Of TResult)
  spec.csharp:
  - uid: OpenTl.Schema.IRequest`1
    name: IRequest
    nameWithType: IRequest
    fullName: OpenTl.Schema.IRequest
  - name: <
    nameWithType: <
    fullName: <
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: OpenTl.Schema.IRequest`1
    name: IRequest
    nameWithType: IRequest
    fullName: OpenTl.Schema.IRequest
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: )
    nameWithType: )
    fullName: )
- uid: OpenTl.Schema
  commentId: N:OpenTl.Schema
  isExternal: false
  name: OpenTl.Schema
  nameWithType: OpenTl.Schema
  fullName: OpenTl.Schema
- uid: OpenTl.Schema.Messages.RequestGetDhConfig.Version*
  commentId: Overload:OpenTl.Schema.Messages.RequestGetDhConfig.Version
  isExternal: false
  name: Version
  nameWithType: RequestGetDhConfig.Version
  fullName: OpenTl.Schema.Messages.RequestGetDhConfig.Version
- uid: System.Int32
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: OpenTl.Schema.Messages.RequestGetDhConfig.RandomLength*
  commentId: Overload:OpenTl.Schema.Messages.RequestGetDhConfig.RandomLength
  isExternal: false
  name: RandomLength
  nameWithType: RequestGetDhConfig.RandomLength
  fullName: OpenTl.Schema.Messages.RequestGetDhConfig.RandomLength
