### YamlMime:ManagedReference
items:
- uid: OpenTl.Schema.Account.TPasswordSettings
  commentId: T:OpenTl.Schema.Account.TPasswordSettings
  id: TPasswordSettings
  parent: OpenTl.Schema.Account
  children:
  - OpenTl.Schema.Account.TPasswordSettings.Email
  - OpenTl.Schema.Account.TPasswordSettings.EmailAsBinary
  langs:
  - csharp
  - vb
  name: TPasswordSettings
  nameWithType: TPasswordSettings
  fullName: OpenTl.Schema.Account.TPasswordSettings
  type: Class
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Account/PasswordSettings/TPasswordSettings.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: TPasswordSettings
    path: ../src/OpenTl.Schema/_generated/Account/PasswordSettings/TPasswordSettings.cs
    startLine: 11
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Account
  syntax:
    content: 'public class TPasswordSettings : object, IPasswordSettings, IObject'
    content.vb: >-
      Public Class TPasswordSettings

          Inherits Object

          Implements IPasswordSettings, IObject
  inheritance:
  - System.Object
  implements:
  - OpenTl.Schema.Account.IPasswordSettings
  - OpenTl.Schema.IObject
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: OpenTl.Schema.Account.TPasswordSettings.EmailAsBinary
  commentId: P:OpenTl.Schema.Account.TPasswordSettings.EmailAsBinary
  id: EmailAsBinary
  parent: OpenTl.Schema.Account.TPasswordSettings
  langs:
  - csharp
  - vb
  name: EmailAsBinary
  nameWithType: TPasswordSettings.EmailAsBinary
  fullName: OpenTl.Schema.Account.TPasswordSettings.EmailAsBinary
  type: Property
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Account/PasswordSettings/TPasswordSettings.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: EmailAsBinary
    path: ../src/OpenTl.Schema/_generated/Account/PasswordSettings/TPasswordSettings.cs
    startLine: 15
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Account
  summary: Binary representation for the &apos;Email&apos; property
  example: []
  syntax:
    content: public byte[] EmailAsBinary { get; set; }
    parameters: []
    return:
      type: System.Byte[]
    content.vb: Public Property EmailAsBinary As Byte()
  overload: OpenTl.Schema.Account.TPasswordSettings.EmailAsBinary*
  implements:
  - OpenTl.Schema.Account.IPasswordSettings.EmailAsBinary
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: OpenTl.Schema.Account.TPasswordSettings.Email
  commentId: P:OpenTl.Schema.Account.TPasswordSettings.Email
  id: Email
  parent: OpenTl.Schema.Account.TPasswordSettings
  langs:
  - csharp
  - vb
  name: Email
  nameWithType: TPasswordSettings.Email
  fullName: OpenTl.Schema.Account.TPasswordSettings.Email
  type: Property
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Account/PasswordSettings/TPasswordSettings.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: Email
    path: ../src/OpenTl.Schema/_generated/Account/PasswordSettings/TPasswordSettings.cs
    startLine: 19
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Account
  syntax:
    content: public string Email { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Email As String
  overload: OpenTl.Schema.Account.TPasswordSettings.Email*
  implements:
  - OpenTl.Schema.Account.IPasswordSettings.Email
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: OpenTl.Schema.Account
  commentId: N:OpenTl.Schema.Account
  isExternal: false
  name: OpenTl.Schema.Account
  nameWithType: OpenTl.Schema.Account
  fullName: OpenTl.Schema.Account
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: OpenTl.Schema.Account.IPasswordSettings
  commentId: T:OpenTl.Schema.Account.IPasswordSettings
  parent: OpenTl.Schema.Account
  isExternal: false
  name: IPasswordSettings
  nameWithType: IPasswordSettings
  fullName: OpenTl.Schema.Account.IPasswordSettings
- uid: OpenTl.Schema.IObject
  commentId: T:OpenTl.Schema.IObject
  parent: OpenTl.Schema
  isExternal: false
  name: IObject
  nameWithType: IObject
  fullName: OpenTl.Schema.IObject
- uid: OpenTl.Schema
  commentId: N:OpenTl.Schema
  isExternal: false
  name: OpenTl.Schema
  nameWithType: OpenTl.Schema
  fullName: OpenTl.Schema
- uid: OpenTl.Schema.Account.TPasswordSettings.EmailAsBinary*
  commentId: Overload:OpenTl.Schema.Account.TPasswordSettings.EmailAsBinary
  isExternal: false
  name: EmailAsBinary
  nameWithType: TPasswordSettings.EmailAsBinary
  fullName: OpenTl.Schema.Account.TPasswordSettings.EmailAsBinary
- uid: OpenTl.Schema.Account.IPasswordSettings.EmailAsBinary
  commentId: P:OpenTl.Schema.Account.IPasswordSettings.EmailAsBinary
  parent: OpenTl.Schema.Account.IPasswordSettings
  isExternal: false
  name: EmailAsBinary
  nameWithType: IPasswordSettings.EmailAsBinary
  fullName: OpenTl.Schema.Account.IPasswordSettings.EmailAsBinary
- uid: System.Byte[]
  name: Byte[]
  nameWithType: Byte[]
  fullName: System.Byte[]
  nameWithType.vb: Byte()
  fullName.vb: System.Byte()
  name.vb: Byte()
  spec.csharp:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
  spec.vb:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: ()
    nameWithType: ()
    fullName: ()
- uid: OpenTl.Schema.Account.TPasswordSettings.Email*
  commentId: Overload:OpenTl.Schema.Account.TPasswordSettings.Email
  isExternal: false
  name: Email
  nameWithType: TPasswordSettings.Email
  fullName: OpenTl.Schema.Account.TPasswordSettings.Email
- uid: OpenTl.Schema.Account.IPasswordSettings.Email
  commentId: P:OpenTl.Schema.Account.IPasswordSettings.Email
  parent: OpenTl.Schema.Account.IPasswordSettings
  isExternal: false
  name: Email
  nameWithType: IPasswordSettings.Email
  fullName: OpenTl.Schema.Account.IPasswordSettings.Email
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
