### YamlMime:ManagedReference
items:
- uid: OpenTl.Schema.Account.RequestGetPasswordSettings
  commentId: T:OpenTl.Schema.Account.RequestGetPasswordSettings
  id: RequestGetPasswordSettings
  parent: OpenTl.Schema.Account
  children:
  - OpenTl.Schema.Account.RequestGetPasswordSettings.CurrentPasswordHash
  langs:
  - csharp
  - vb
  name: RequestGetPasswordSettings
  nameWithType: RequestGetPasswordSettings
  fullName: OpenTl.Schema.Account.RequestGetPasswordSettings
  type: Class
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Account/RequestGetPasswordSettings.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: RequestGetPasswordSettings
    path: ../src/OpenTl.Schema/_generated/Account/RequestGetPasswordSettings.cs
    startLine: 11
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Account
  syntax:
    content: 'public class RequestGetPasswordSettings : object, IRequest<IPasswordSettings>, IRequest, IObject'
    content.vb: >-
      Public Class RequestGetPasswordSettings

          Inherits Object

          Implements IRequest(Of IPasswordSettings), IRequest, IObject
  inheritance:
  - System.Object
  implements:
  - OpenTl.Schema.IRequest{OpenTl.Schema.Account.IPasswordSettings}
  - OpenTl.Schema.IRequest
  - OpenTl.Schema.IObject
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: OpenTl.Schema.Account.RequestGetPasswordSettings.CurrentPasswordHash
  commentId: P:OpenTl.Schema.Account.RequestGetPasswordSettings.CurrentPasswordHash
  id: CurrentPasswordHash
  parent: OpenTl.Schema.Account.RequestGetPasswordSettings
  langs:
  - csharp
  - vb
  name: CurrentPasswordHash
  nameWithType: RequestGetPasswordSettings.CurrentPasswordHash
  fullName: OpenTl.Schema.Account.RequestGetPasswordSettings.CurrentPasswordHash
  type: Property
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Account/RequestGetPasswordSettings.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: CurrentPasswordHash
    path: ../src/OpenTl.Schema/_generated/Account/RequestGetPasswordSettings.cs
    startLine: 14
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Account
  syntax:
    content: public byte[] CurrentPasswordHash { get; set; }
    parameters: []
    return:
      type: System.Byte[]
    content.vb: Public Property CurrentPasswordHash As Byte()
  overload: OpenTl.Schema.Account.RequestGetPasswordSettings.CurrentPasswordHash*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: OpenTl.Schema.Account
  commentId: N:OpenTl.Schema.Account
  isExternal: false
  name: OpenTl.Schema.Account
  nameWithType: OpenTl.Schema.Account
  fullName: OpenTl.Schema.Account
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: OpenTl.Schema.IRequest{OpenTl.Schema.Account.IPasswordSettings}
  commentId: T:OpenTl.Schema.IRequest{OpenTl.Schema.Account.IPasswordSettings}
  parent: OpenTl.Schema
  definition: OpenTl.Schema.IRequest`1
  name: IRequest<IPasswordSettings>
  nameWithType: IRequest<IPasswordSettings>
  fullName: OpenTl.Schema.IRequest<OpenTl.Schema.Account.IPasswordSettings>
  nameWithType.vb: IRequest(Of IPasswordSettings)
  fullName.vb: OpenTl.Schema.IRequest(Of OpenTl.Schema.Account.IPasswordSettings)
  name.vb: IRequest(Of IPasswordSettings)
  spec.csharp:
  - uid: OpenTl.Schema.IRequest`1
    name: IRequest
    nameWithType: IRequest
    fullName: OpenTl.Schema.IRequest
  - name: <
    nameWithType: <
    fullName: <
  - uid: OpenTl.Schema.Account.IPasswordSettings
    name: IPasswordSettings
    nameWithType: IPasswordSettings
    fullName: OpenTl.Schema.Account.IPasswordSettings
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: OpenTl.Schema.IRequest`1
    name: IRequest
    nameWithType: IRequest
    fullName: OpenTl.Schema.IRequest
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: OpenTl.Schema.Account.IPasswordSettings
    name: IPasswordSettings
    nameWithType: IPasswordSettings
    fullName: OpenTl.Schema.Account.IPasswordSettings
  - name: )
    nameWithType: )
    fullName: )
- uid: OpenTl.Schema.IRequest
  commentId: T:OpenTl.Schema.IRequest
  parent: OpenTl.Schema
  isExternal: false
  name: IRequest
  nameWithType: IRequest
  fullName: OpenTl.Schema.IRequest
- uid: OpenTl.Schema.IObject
  commentId: T:OpenTl.Schema.IObject
  parent: OpenTl.Schema
  isExternal: false
  name: IObject
  nameWithType: IObject
  fullName: OpenTl.Schema.IObject
- uid: OpenTl.Schema.IRequest`1
  commentId: T:OpenTl.Schema.IRequest`1
  isExternal: false
  name: IRequest<TResult>
  nameWithType: IRequest<TResult>
  fullName: OpenTl.Schema.IRequest<TResult>
  nameWithType.vb: IRequest(Of TResult)
  fullName.vb: OpenTl.Schema.IRequest(Of TResult)
  name.vb: IRequest(Of TResult)
  spec.csharp:
  - uid: OpenTl.Schema.IRequest`1
    name: IRequest
    nameWithType: IRequest
    fullName: OpenTl.Schema.IRequest
  - name: <
    nameWithType: <
    fullName: <
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: OpenTl.Schema.IRequest`1
    name: IRequest
    nameWithType: IRequest
    fullName: OpenTl.Schema.IRequest
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: )
    nameWithType: )
    fullName: )
- uid: OpenTl.Schema
  commentId: N:OpenTl.Schema
  isExternal: false
  name: OpenTl.Schema
  nameWithType: OpenTl.Schema
  fullName: OpenTl.Schema
- uid: OpenTl.Schema.Account.RequestGetPasswordSettings.CurrentPasswordHash*
  commentId: Overload:OpenTl.Schema.Account.RequestGetPasswordSettings.CurrentPasswordHash
  isExternal: false
  name: CurrentPasswordHash
  nameWithType: RequestGetPasswordSettings.CurrentPasswordHash
  fullName: OpenTl.Schema.Account.RequestGetPasswordSettings.CurrentPasswordHash
- uid: System.Byte[]
  name: Byte[]
  nameWithType: Byte[]
  fullName: System.Byte[]
  nameWithType.vb: Byte()
  fullName.vb: System.Byte()
  name.vb: Byte()
  spec.csharp:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
  spec.vb:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: ()
    nameWithType: ()
    fullName: ()
