### YamlMime:ManagedReference
items:
- uid: OpenTl.Schema.TPeerNotifySettingsEmpty
  commentId: T:OpenTl.Schema.TPeerNotifySettingsEmpty
  id: TPeerNotifySettingsEmpty
  parent: OpenTl.Schema
  children: []
  langs:
  - csharp
  - vb
  name: TPeerNotifySettingsEmpty
  nameWithType: TPeerNotifySettingsEmpty
  fullName: OpenTl.Schema.TPeerNotifySettingsEmpty
  type: Class
  source:
    remote:
      path: src/OpenTl.Schema/_generated/_Entities/PeerNotifySettings/TPeerNotifySettingsEmpty.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: TPeerNotifySettingsEmpty
    path: ../src/OpenTl.Schema/_generated/_Entities/PeerNotifySettings/TPeerNotifySettingsEmpty.cs
    startLine: 11
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema
  syntax:
    content: 'public class TPeerNotifySettingsEmpty : object, IPeerNotifySettings, IObject, IEmpty'
    content.vb: >-
      Public Class TPeerNotifySettingsEmpty

          Inherits Object

          Implements IPeerNotifySettings, IObject, IEmpty
  inheritance:
  - System.Object
  implements:
  - OpenTl.Schema.IPeerNotifySettings
  - OpenTl.Schema.IObject
  - OpenTl.Schema.IEmpty
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
references:
- uid: OpenTl.Schema
  commentId: N:OpenTl.Schema
  isExternal: false
  name: OpenTl.Schema
  nameWithType: OpenTl.Schema
  fullName: OpenTl.Schema
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: OpenTl.Schema.IPeerNotifySettings
  commentId: T:OpenTl.Schema.IPeerNotifySettings
  parent: OpenTl.Schema
  isExternal: false
  name: IPeerNotifySettings
  nameWithType: IPeerNotifySettings
  fullName: OpenTl.Schema.IPeerNotifySettings
- uid: OpenTl.Schema.IObject
  commentId: T:OpenTl.Schema.IObject
  parent: OpenTl.Schema
  isExternal: false
  name: IObject
  nameWithType: IObject
  fullName: OpenTl.Schema.IObject
- uid: OpenTl.Schema.IEmpty
  commentId: T:OpenTl.Schema.IEmpty
  parent: OpenTl.Schema
  isExternal: false
  name: IEmpty
  nameWithType: IEmpty
  fullName: OpenTl.Schema.IEmpty
