### YamlMime:ManagedReference
items:
- uid: OpenTl.Schema.Account.RequestResetNotifySettings
  commentId: T:OpenTl.Schema.Account.RequestResetNotifySettings
  id: RequestResetNotifySettings
  parent: OpenTl.Schema.Account
  children: []
  langs:
  - csharp
  - vb
  name: RequestResetNotifySettings
  nameWithType: RequestResetNotifySettings
  fullName: OpenTl.Schema.Account.RequestResetNotifySettings
  type: Class
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Account/RequestResetNotifySettings.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: RequestResetNotifySettings
    path: ../src/OpenTl.Schema/_generated/Account/RequestResetNotifySettings.cs
    startLine: 11
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Account
  syntax:
    content: 'public class RequestResetNotifySettings : object, IRequest<bool>, IRequest, IObject'
    content.vb: >-
      Public Class RequestResetNotifySettings

          Inherits Object

          Implements IRequest(Of Boolean), IRequest, IObject
  inheritance:
  - System.Object
  implements:
  - OpenTl.Schema.IRequest{System.Boolean}
  - OpenTl.Schema.IRequest
  - OpenTl.Schema.IObject
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
references:
- uid: OpenTl.Schema.Account
  commentId: N:OpenTl.Schema.Account
  isExternal: false
  name: OpenTl.Schema.Account
  nameWithType: OpenTl.Schema.Account
  fullName: OpenTl.Schema.Account
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: OpenTl.Schema.IRequest{System.Boolean}
  commentId: T:OpenTl.Schema.IRequest{System.Boolean}
  parent: OpenTl.Schema
  definition: OpenTl.Schema.IRequest`1
  name: IRequest<Boolean>
  nameWithType: IRequest<Boolean>
  fullName: OpenTl.Schema.IRequest<System.Boolean>
  nameWithType.vb: IRequest(Of Boolean)
  fullName.vb: OpenTl.Schema.IRequest(Of System.Boolean)
  name.vb: IRequest(Of Boolean)
  spec.csharp:
  - uid: OpenTl.Schema.IRequest`1
    name: IRequest
    nameWithType: IRequest
    fullName: OpenTl.Schema.IRequest
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: OpenTl.Schema.IRequest`1
    name: IRequest
    nameWithType: IRequest
    fullName: OpenTl.Schema.IRequest
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: OpenTl.Schema.IRequest
  commentId: T:OpenTl.Schema.IRequest
  parent: OpenTl.Schema
  isExternal: false
  name: IRequest
  nameWithType: IRequest
  fullName: OpenTl.Schema.IRequest
- uid: OpenTl.Schema.IObject
  commentId: T:OpenTl.Schema.IObject
  parent: OpenTl.Schema
  isExternal: false
  name: IObject
  nameWithType: IObject
  fullName: OpenTl.Schema.IObject
- uid: OpenTl.Schema.IRequest`1
  commentId: T:OpenTl.Schema.IRequest`1
  isExternal: false
  name: IRequest<TResult>
  nameWithType: IRequest<TResult>
  fullName: OpenTl.Schema.IRequest<TResult>
  nameWithType.vb: IRequest(Of TResult)
  fullName.vb: OpenTl.Schema.IRequest(Of TResult)
  name.vb: IRequest(Of TResult)
  spec.csharp:
  - uid: OpenTl.Schema.IRequest`1
    name: IRequest
    nameWithType: IRequest
    fullName: OpenTl.Schema.IRequest
  - name: <
    nameWithType: <
    fullName: <
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: OpenTl.Schema.IRequest`1
    name: IRequest
    nameWithType: IRequest
    fullName: OpenTl.Schema.IRequest
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: )
    nameWithType: )
    fullName: )
- uid: OpenTl.Schema
  commentId: N:OpenTl.Schema
  isExternal: false
  name: OpenTl.Schema
  nameWithType: OpenTl.Schema
  fullName: OpenTl.Schema
