### YamlMime:ManagedReference
items:
- uid: OpenTl.Schema.Account.RequestUpdatePasswordSettings
  commentId: T:OpenTl.Schema.Account.RequestUpdatePasswordSettings
  id: RequestUpdatePasswordSettings
  parent: OpenTl.Schema.Account
  children:
  - OpenTl.Schema.Account.RequestUpdatePasswordSettings.CurrentPasswordHash
  - OpenTl.Schema.Account.RequestUpdatePasswordSettings.NewSettings
  langs:
  - csharp
  - vb
  name: RequestUpdatePasswordSettings
  nameWithType: RequestUpdatePasswordSettings
  fullName: OpenTl.Schema.Account.RequestUpdatePasswordSettings
  type: Class
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Account/RequestUpdatePasswordSettings.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: RequestUpdatePasswordSettings
    path: ../src/OpenTl.Schema/_generated/Account/RequestUpdatePasswordSettings.cs
    startLine: 11
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Account
  syntax:
    content: 'public class RequestUpdatePasswordSettings : object, IRequest<bool>, IRequest, IObject'
    content.vb: >-
      Public Class RequestUpdatePasswordSettings

          Inherits Object

          Implements IRequest(Of Boolean), IRequest, IObject
  inheritance:
  - System.Object
  implements:
  - OpenTl.Schema.IRequest{System.Boolean}
  - OpenTl.Schema.IRequest
  - OpenTl.Schema.IObject
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: OpenTl.Schema.Account.RequestUpdatePasswordSettings.CurrentPasswordHash
  commentId: P:OpenTl.Schema.Account.RequestUpdatePasswordSettings.CurrentPasswordHash
  id: CurrentPasswordHash
  parent: OpenTl.Schema.Account.RequestUpdatePasswordSettings
  langs:
  - csharp
  - vb
  name: CurrentPasswordHash
  nameWithType: RequestUpdatePasswordSettings.CurrentPasswordHash
  fullName: OpenTl.Schema.Account.RequestUpdatePasswordSettings.CurrentPasswordHash
  type: Property
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Account/RequestUpdatePasswordSettings.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: CurrentPasswordHash
    path: ../src/OpenTl.Schema/_generated/Account/RequestUpdatePasswordSettings.cs
    startLine: 14
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Account
  syntax:
    content: public byte[] CurrentPasswordHash { get; set; }
    parameters: []
    return:
      type: System.Byte[]
    content.vb: Public Property CurrentPasswordHash As Byte()
  overload: OpenTl.Schema.Account.RequestUpdatePasswordSettings.CurrentPasswordHash*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: OpenTl.Schema.Account.RequestUpdatePasswordSettings.NewSettings
  commentId: P:OpenTl.Schema.Account.RequestUpdatePasswordSettings.NewSettings
  id: NewSettings
  parent: OpenTl.Schema.Account.RequestUpdatePasswordSettings
  langs:
  - csharp
  - vb
  name: NewSettings
  nameWithType: RequestUpdatePasswordSettings.NewSettings
  fullName: OpenTl.Schema.Account.RequestUpdatePasswordSettings.NewSettings
  type: Property
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Account/RequestUpdatePasswordSettings.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: NewSettings
    path: ../src/OpenTl.Schema/_generated/Account/RequestUpdatePasswordSettings.cs
    startLine: 17
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Account
  syntax:
    content: public IPasswordInputSettings NewSettings { get; set; }
    parameters: []
    return:
      type: OpenTl.Schema.Account.IPasswordInputSettings
    content.vb: Public Property NewSettings As IPasswordInputSettings
  overload: OpenTl.Schema.Account.RequestUpdatePasswordSettings.NewSettings*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: OpenTl.Schema.Account
  commentId: N:OpenTl.Schema.Account
  isExternal: false
  name: OpenTl.Schema.Account
  nameWithType: OpenTl.Schema.Account
  fullName: OpenTl.Schema.Account
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: OpenTl.Schema.IRequest{System.Boolean}
  commentId: T:OpenTl.Schema.IRequest{System.Boolean}
  parent: OpenTl.Schema
  definition: OpenTl.Schema.IRequest`1
  name: IRequest<Boolean>
  nameWithType: IRequest<Boolean>
  fullName: OpenTl.Schema.IRequest<System.Boolean>
  nameWithType.vb: IRequest(Of Boolean)
  fullName.vb: OpenTl.Schema.IRequest(Of System.Boolean)
  name.vb: IRequest(Of Boolean)
  spec.csharp:
  - uid: OpenTl.Schema.IRequest`1
    name: IRequest
    nameWithType: IRequest
    fullName: OpenTl.Schema.IRequest
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: OpenTl.Schema.IRequest`1
    name: IRequest
    nameWithType: IRequest
    fullName: OpenTl.Schema.IRequest
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: OpenTl.Schema.IRequest
  commentId: T:OpenTl.Schema.IRequest
  parent: OpenTl.Schema
  isExternal: false
  name: IRequest
  nameWithType: IRequest
  fullName: OpenTl.Schema.IRequest
- uid: OpenTl.Schema.IObject
  commentId: T:OpenTl.Schema.IObject
  parent: OpenTl.Schema
  isExternal: false
  name: IObject
  nameWithType: IObject
  fullName: OpenTl.Schema.IObject
- uid: OpenTl.Schema.IRequest`1
  commentId: T:OpenTl.Schema.IRequest`1
  isExternal: false
  name: IRequest<TResult>
  nameWithType: IRequest<TResult>
  fullName: OpenTl.Schema.IRequest<TResult>
  nameWithType.vb: IRequest(Of TResult)
  fullName.vb: OpenTl.Schema.IRequest(Of TResult)
  name.vb: IRequest(Of TResult)
  spec.csharp:
  - uid: OpenTl.Schema.IRequest`1
    name: IRequest
    nameWithType: IRequest
    fullName: OpenTl.Schema.IRequest
  - name: <
    nameWithType: <
    fullName: <
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: OpenTl.Schema.IRequest`1
    name: IRequest
    nameWithType: IRequest
    fullName: OpenTl.Schema.IRequest
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: )
    nameWithType: )
    fullName: )
- uid: OpenTl.Schema
  commentId: N:OpenTl.Schema
  isExternal: false
  name: OpenTl.Schema
  nameWithType: OpenTl.Schema
  fullName: OpenTl.Schema
- uid: OpenTl.Schema.Account.RequestUpdatePasswordSettings.CurrentPasswordHash*
  commentId: Overload:OpenTl.Schema.Account.RequestUpdatePasswordSettings.CurrentPasswordHash
  isExternal: false
  name: CurrentPasswordHash
  nameWithType: RequestUpdatePasswordSettings.CurrentPasswordHash
  fullName: OpenTl.Schema.Account.RequestUpdatePasswordSettings.CurrentPasswordHash
- uid: System.Byte[]
  name: Byte[]
  nameWithType: Byte[]
  fullName: System.Byte[]
  nameWithType.vb: Byte()
  fullName.vb: System.Byte()
  name.vb: Byte()
  spec.csharp:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
  spec.vb:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: ()
    nameWithType: ()
    fullName: ()
- uid: OpenTl.Schema.Account.RequestUpdatePasswordSettings.NewSettings*
  commentId: Overload:OpenTl.Schema.Account.RequestUpdatePasswordSettings.NewSettings
  isExternal: false
  name: NewSettings
  nameWithType: RequestUpdatePasswordSettings.NewSettings
  fullName: OpenTl.Schema.Account.RequestUpdatePasswordSettings.NewSettings
- uid: OpenTl.Schema.Account.IPasswordInputSettings
  commentId: T:OpenTl.Schema.Account.IPasswordInputSettings
  parent: OpenTl.Schema.Account
  isExternal: false
  name: IPasswordInputSettings
  nameWithType: IPasswordInputSettings
  fullName: OpenTl.Schema.Account.IPasswordInputSettings
