### YamlMime:ManagedReference
items:
- uid: OpenTl.Schema.Account.IPasswordInputSettings
  commentId: T:OpenTl.Schema.Account.IPasswordInputSettings
  id: IPasswordInputSettings
  parent: OpenTl.Schema.Account
  children:
  - OpenTl.Schema.Account.IPasswordInputSettings.Email
  - OpenTl.Schema.Account.IPasswordInputSettings.EmailAsBinary
  - OpenTl.Schema.Account.IPasswordInputSettings.Flags
  - OpenTl.Schema.Account.IPasswordInputSettings.Hint
  - OpenTl.Schema.Account.IPasswordInputSettings.HintAsBinary
  - OpenTl.Schema.Account.IPasswordInputSettings.NewPasswordHash
  - OpenTl.Schema.Account.IPasswordInputSettings.NewSalt
  langs:
  - csharp
  - vb
  name: IPasswordInputSettings
  nameWithType: IPasswordInputSettings
  fullName: OpenTl.Schema.Account.IPasswordInputSettings
  type: Interface
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Account/PasswordInputSettings/IPasswordInputSettings.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: IPasswordInputSettings
    path: ../src/OpenTl.Schema/_generated/Account/PasswordInputSettings/IPasswordInputSettings.cs
    startLine: 9
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Account
  syntax:
    content: 'public interface IPasswordInputSettings : IObject'
    content.vb: >-
      Public Interface IPasswordInputSettings

          Inherits IObject
  extensionMethods:
  - OpenTl.Schema.IObject.OpenTl.Schema.Utils.As``1
  - OpenTl.Schema.IObject.OpenTl.Schema.Utils.Cast``1
  - OpenTl.Schema.IObject.OpenTl.Schema.Utils.IsEmpty
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: OpenTl.Schema.Account.IPasswordInputSettings.Flags
  commentId: P:OpenTl.Schema.Account.IPasswordInputSettings.Flags
  id: Flags
  parent: OpenTl.Schema.Account.IPasswordInputSettings
  langs:
  - csharp
  - vb
  name: Flags
  nameWithType: IPasswordInputSettings.Flags
  fullName: OpenTl.Schema.Account.IPasswordInputSettings.Flags
  type: Property
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Account/PasswordInputSettings/IPasswordInputSettings.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: Flags
    path: ../src/OpenTl.Schema/_generated/Account/PasswordInputSettings/IPasswordInputSettings.cs
    startLine: 11
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Account
  syntax:
    content: BitArray Flags { get; set; }
    parameters: []
    return:
      type: BitArray
    content.vb: Property Flags As BitArray
  overload: OpenTl.Schema.Account.IPasswordInputSettings.Flags*
  modifiers.csharp:
  - get
  - set
- uid: OpenTl.Schema.Account.IPasswordInputSettings.NewSalt
  commentId: P:OpenTl.Schema.Account.IPasswordInputSettings.NewSalt
  id: NewSalt
  parent: OpenTl.Schema.Account.IPasswordInputSettings
  langs:
  - csharp
  - vb
  name: NewSalt
  nameWithType: IPasswordInputSettings.NewSalt
  fullName: OpenTl.Schema.Account.IPasswordInputSettings.NewSalt
  type: Property
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Account/PasswordInputSettings/IPasswordInputSettings.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: NewSalt
    path: ../src/OpenTl.Schema/_generated/Account/PasswordInputSettings/IPasswordInputSettings.cs
    startLine: 13
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Account
  syntax:
    content: byte[] NewSalt { get; set; }
    parameters: []
    return:
      type: System.Byte[]
    content.vb: Property NewSalt As Byte()
  overload: OpenTl.Schema.Account.IPasswordInputSettings.NewSalt*
  modifiers.csharp:
  - get
  - set
- uid: OpenTl.Schema.Account.IPasswordInputSettings.NewPasswordHash
  commentId: P:OpenTl.Schema.Account.IPasswordInputSettings.NewPasswordHash
  id: NewPasswordHash
  parent: OpenTl.Schema.Account.IPasswordInputSettings
  langs:
  - csharp
  - vb
  name: NewPasswordHash
  nameWithType: IPasswordInputSettings.NewPasswordHash
  fullName: OpenTl.Schema.Account.IPasswordInputSettings.NewPasswordHash
  type: Property
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Account/PasswordInputSettings/IPasswordInputSettings.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: NewPasswordHash
    path: ../src/OpenTl.Schema/_generated/Account/PasswordInputSettings/IPasswordInputSettings.cs
    startLine: 15
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Account
  syntax:
    content: byte[] NewPasswordHash { get; set; }
    parameters: []
    return:
      type: System.Byte[]
    content.vb: Property NewPasswordHash As Byte()
  overload: OpenTl.Schema.Account.IPasswordInputSettings.NewPasswordHash*
  modifiers.csharp:
  - get
  - set
- uid: OpenTl.Schema.Account.IPasswordInputSettings.HintAsBinary
  commentId: P:OpenTl.Schema.Account.IPasswordInputSettings.HintAsBinary
  id: HintAsBinary
  parent: OpenTl.Schema.Account.IPasswordInputSettings
  langs:
  - csharp
  - vb
  name: HintAsBinary
  nameWithType: IPasswordInputSettings.HintAsBinary
  fullName: OpenTl.Schema.Account.IPasswordInputSettings.HintAsBinary
  type: Property
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Account/PasswordInputSettings/IPasswordInputSettings.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: HintAsBinary
    path: ../src/OpenTl.Schema/_generated/Account/PasswordInputSettings/IPasswordInputSettings.cs
    startLine: 17
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Account
  syntax:
    content: byte[] HintAsBinary { get; set; }
    parameters: []
    return:
      type: System.Byte[]
    content.vb: Property HintAsBinary As Byte()
  overload: OpenTl.Schema.Account.IPasswordInputSettings.HintAsBinary*
  modifiers.csharp:
  - get
  - set
- uid: OpenTl.Schema.Account.IPasswordInputSettings.Hint
  commentId: P:OpenTl.Schema.Account.IPasswordInputSettings.Hint
  id: Hint
  parent: OpenTl.Schema.Account.IPasswordInputSettings
  langs:
  - csharp
  - vb
  name: Hint
  nameWithType: IPasswordInputSettings.Hint
  fullName: OpenTl.Schema.Account.IPasswordInputSettings.Hint
  type: Property
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Account/PasswordInputSettings/IPasswordInputSettings.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: Hint
    path: ../src/OpenTl.Schema/_generated/Account/PasswordInputSettings/IPasswordInputSettings.cs
    startLine: 18
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Account
  syntax:
    content: string Hint { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property Hint As String
  overload: OpenTl.Schema.Account.IPasswordInputSettings.Hint*
  modifiers.csharp:
  - get
  - set
- uid: OpenTl.Schema.Account.IPasswordInputSettings.EmailAsBinary
  commentId: P:OpenTl.Schema.Account.IPasswordInputSettings.EmailAsBinary
  id: EmailAsBinary
  parent: OpenTl.Schema.Account.IPasswordInputSettings
  langs:
  - csharp
  - vb
  name: EmailAsBinary
  nameWithType: IPasswordInputSettings.EmailAsBinary
  fullName: OpenTl.Schema.Account.IPasswordInputSettings.EmailAsBinary
  type: Property
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Account/PasswordInputSettings/IPasswordInputSettings.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: EmailAsBinary
    path: ../src/OpenTl.Schema/_generated/Account/PasswordInputSettings/IPasswordInputSettings.cs
    startLine: 20
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Account
  syntax:
    content: byte[] EmailAsBinary { get; set; }
    parameters: []
    return:
      type: System.Byte[]
    content.vb: Property EmailAsBinary As Byte()
  overload: OpenTl.Schema.Account.IPasswordInputSettings.EmailAsBinary*
  modifiers.csharp:
  - get
  - set
- uid: OpenTl.Schema.Account.IPasswordInputSettings.Email
  commentId: P:OpenTl.Schema.Account.IPasswordInputSettings.Email
  id: Email
  parent: OpenTl.Schema.Account.IPasswordInputSettings
  langs:
  - csharp
  - vb
  name: Email
  nameWithType: IPasswordInputSettings.Email
  fullName: OpenTl.Schema.Account.IPasswordInputSettings.Email
  type: Property
  source:
    remote:
      path: src/OpenTl.Schema/_generated/Account/PasswordInputSettings/IPasswordInputSettings.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: Email
    path: ../src/OpenTl.Schema/_generated/Account/PasswordInputSettings/IPasswordInputSettings.cs
    startLine: 21
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema.Account
  syntax:
    content: string Email { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property Email As String
  overload: OpenTl.Schema.Account.IPasswordInputSettings.Email*
  modifiers.csharp:
  - get
  - set
references:
- uid: OpenTl.Schema.Account
  commentId: N:OpenTl.Schema.Account
  isExternal: false
  name: OpenTl.Schema.Account
  nameWithType: OpenTl.Schema.Account
  fullName: OpenTl.Schema.Account
- uid: OpenTl.Schema.IObject.OpenTl.Schema.Utils.As``1
  commentId: M:OpenTl.Schema.Utils.As``1(OpenTl.Schema.IObject)
  parent: OpenTl.Schema.Utils
  definition: OpenTl.Schema.Utils.As``1(OpenTl.Schema.IObject)
  name: As<T>()
  nameWithType: Utils.As<T>()
  fullName: OpenTl.Schema.Utils.As<T>()
  nameWithType.vb: Utils.As(Of T)()
  fullName.vb: OpenTl.Schema.Utils.As(Of T)()
  name.vb: As(Of T)()
  spec.csharp:
  - uid: OpenTl.Schema.Utils.As``1
    name: As<T>
    nameWithType: Utils.As<T>
    fullName: OpenTl.Schema.Utils.As<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: OpenTl.Schema.Utils.As``1
    name: As(Of T)
    nameWithType: Utils.As(Of T)
    fullName: OpenTl.Schema.Utils.As(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: OpenTl.Schema.IObject.OpenTl.Schema.Utils.Cast``1
  commentId: M:OpenTl.Schema.Utils.Cast``1(OpenTl.Schema.IObject)
  parent: OpenTl.Schema.Utils
  definition: OpenTl.Schema.Utils.Cast``1(OpenTl.Schema.IObject)
  name: Cast<T>()
  nameWithType: Utils.Cast<T>()
  fullName: OpenTl.Schema.Utils.Cast<T>()
  nameWithType.vb: Utils.Cast(Of T)()
  fullName.vb: OpenTl.Schema.Utils.Cast(Of T)()
  name.vb: Cast(Of T)()
  spec.csharp:
  - uid: OpenTl.Schema.Utils.Cast``1
    name: Cast<T>
    nameWithType: Utils.Cast<T>
    fullName: OpenTl.Schema.Utils.Cast<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: OpenTl.Schema.Utils.Cast``1
    name: Cast(Of T)
    nameWithType: Utils.Cast(Of T)
    fullName: OpenTl.Schema.Utils.Cast(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: OpenTl.Schema.IObject.OpenTl.Schema.Utils.IsEmpty
  commentId: M:OpenTl.Schema.Utils.IsEmpty(OpenTl.Schema.IObject)
  parent: OpenTl.Schema.Utils
  definition: OpenTl.Schema.Utils.IsEmpty(OpenTl.Schema.IObject)
  name: IsEmpty()
  nameWithType: Utils.IsEmpty()
  fullName: OpenTl.Schema.Utils.IsEmpty()
  spec.csharp:
  - uid: OpenTl.Schema.Utils.IsEmpty
    name: IsEmpty
    nameWithType: Utils.IsEmpty
    fullName: OpenTl.Schema.Utils.IsEmpty
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: OpenTl.Schema.Utils.IsEmpty
    name: IsEmpty
    nameWithType: Utils.IsEmpty
    fullName: OpenTl.Schema.Utils.IsEmpty
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: OpenTl.Schema.Utils.As``1(OpenTl.Schema.IObject)
  commentId: M:OpenTl.Schema.Utils.As``1(OpenTl.Schema.IObject)
  isExternal: false
  name: As<T>(IObject)
  nameWithType: Utils.As<T>(IObject)
  fullName: OpenTl.Schema.Utils.As<T>(OpenTl.Schema.IObject)
  nameWithType.vb: Utils.As(Of T)(IObject)
  fullName.vb: OpenTl.Schema.Utils.As(Of T)(OpenTl.Schema.IObject)
  name.vb: As(Of T)(IObject)
  spec.csharp:
  - uid: OpenTl.Schema.Utils.As``1(OpenTl.Schema.IObject)
    name: As<T>
    nameWithType: Utils.As<T>
    fullName: OpenTl.Schema.Utils.As<T>
  - name: (
    nameWithType: (
    fullName: (
  - uid: OpenTl.Schema.IObject
    name: IObject
    nameWithType: IObject
    fullName: OpenTl.Schema.IObject
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: OpenTl.Schema.Utils.As``1(OpenTl.Schema.IObject)
    name: As(Of T)
    nameWithType: Utils.As(Of T)
    fullName: OpenTl.Schema.Utils.As(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - uid: OpenTl.Schema.IObject
    name: IObject
    nameWithType: IObject
    fullName: OpenTl.Schema.IObject
  - name: )
    nameWithType: )
    fullName: )
- uid: OpenTl.Schema.Utils
  commentId: T:OpenTl.Schema.Utils
  parent: OpenTl.Schema
  isExternal: false
  name: Utils
  nameWithType: Utils
  fullName: OpenTl.Schema.Utils
- uid: OpenTl.Schema.Utils.Cast``1(OpenTl.Schema.IObject)
  commentId: M:OpenTl.Schema.Utils.Cast``1(OpenTl.Schema.IObject)
  isExternal: false
  name: Cast<T>(IObject)
  nameWithType: Utils.Cast<T>(IObject)
  fullName: OpenTl.Schema.Utils.Cast<T>(OpenTl.Schema.IObject)
  nameWithType.vb: Utils.Cast(Of T)(IObject)
  fullName.vb: OpenTl.Schema.Utils.Cast(Of T)(OpenTl.Schema.IObject)
  name.vb: Cast(Of T)(IObject)
  spec.csharp:
  - uid: OpenTl.Schema.Utils.Cast``1(OpenTl.Schema.IObject)
    name: Cast<T>
    nameWithType: Utils.Cast<T>
    fullName: OpenTl.Schema.Utils.Cast<T>
  - name: (
    nameWithType: (
    fullName: (
  - uid: OpenTl.Schema.IObject
    name: IObject
    nameWithType: IObject
    fullName: OpenTl.Schema.IObject
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: OpenTl.Schema.Utils.Cast``1(OpenTl.Schema.IObject)
    name: Cast(Of T)
    nameWithType: Utils.Cast(Of T)
    fullName: OpenTl.Schema.Utils.Cast(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - uid: OpenTl.Schema.IObject
    name: IObject
    nameWithType: IObject
    fullName: OpenTl.Schema.IObject
  - name: )
    nameWithType: )
    fullName: )
- uid: OpenTl.Schema.Utils.IsEmpty(OpenTl.Schema.IObject)
  commentId: M:OpenTl.Schema.Utils.IsEmpty(OpenTl.Schema.IObject)
  isExternal: false
  name: IsEmpty(IObject)
  nameWithType: Utils.IsEmpty(IObject)
  fullName: OpenTl.Schema.Utils.IsEmpty(OpenTl.Schema.IObject)
  spec.csharp:
  - uid: OpenTl.Schema.Utils.IsEmpty(OpenTl.Schema.IObject)
    name: IsEmpty
    nameWithType: Utils.IsEmpty
    fullName: OpenTl.Schema.Utils.IsEmpty
  - name: (
    nameWithType: (
    fullName: (
  - uid: OpenTl.Schema.IObject
    name: IObject
    nameWithType: IObject
    fullName: OpenTl.Schema.IObject
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: OpenTl.Schema.Utils.IsEmpty(OpenTl.Schema.IObject)
    name: IsEmpty
    nameWithType: Utils.IsEmpty
    fullName: OpenTl.Schema.Utils.IsEmpty
  - name: (
    nameWithType: (
    fullName: (
  - uid: OpenTl.Schema.IObject
    name: IObject
    nameWithType: IObject
    fullName: OpenTl.Schema.IObject
  - name: )
    nameWithType: )
    fullName: )
- uid: OpenTl.Schema
  commentId: N:OpenTl.Schema
  isExternal: false
  name: OpenTl.Schema
  nameWithType: OpenTl.Schema
  fullName: OpenTl.Schema
- uid: OpenTl.Schema.Account.IPasswordInputSettings.Flags*
  commentId: Overload:OpenTl.Schema.Account.IPasswordInputSettings.Flags
  isExternal: false
  name: Flags
  nameWithType: IPasswordInputSettings.Flags
  fullName: OpenTl.Schema.Account.IPasswordInputSettings.Flags
- uid: BitArray
  isExternal: true
  name: BitArray
  nameWithType: BitArray
  fullName: BitArray
- uid: OpenTl.Schema.Account.IPasswordInputSettings.NewSalt*
  commentId: Overload:OpenTl.Schema.Account.IPasswordInputSettings.NewSalt
  isExternal: false
  name: NewSalt
  nameWithType: IPasswordInputSettings.NewSalt
  fullName: OpenTl.Schema.Account.IPasswordInputSettings.NewSalt
- uid: System.Byte[]
  name: Byte[]
  nameWithType: Byte[]
  fullName: System.Byte[]
  nameWithType.vb: Byte()
  fullName.vb: System.Byte()
  name.vb: Byte()
  spec.csharp:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
  spec.vb:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: ()
    nameWithType: ()
    fullName: ()
- uid: OpenTl.Schema.Account.IPasswordInputSettings.NewPasswordHash*
  commentId: Overload:OpenTl.Schema.Account.IPasswordInputSettings.NewPasswordHash
  isExternal: false
  name: NewPasswordHash
  nameWithType: IPasswordInputSettings.NewPasswordHash
  fullName: OpenTl.Schema.Account.IPasswordInputSettings.NewPasswordHash
- uid: OpenTl.Schema.Account.IPasswordInputSettings.HintAsBinary*
  commentId: Overload:OpenTl.Schema.Account.IPasswordInputSettings.HintAsBinary
  isExternal: false
  name: HintAsBinary
  nameWithType: IPasswordInputSettings.HintAsBinary
  fullName: OpenTl.Schema.Account.IPasswordInputSettings.HintAsBinary
- uid: OpenTl.Schema.Account.IPasswordInputSettings.Hint*
  commentId: Overload:OpenTl.Schema.Account.IPasswordInputSettings.Hint
  isExternal: false
  name: Hint
  nameWithType: IPasswordInputSettings.Hint
  fullName: OpenTl.Schema.Account.IPasswordInputSettings.Hint
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: OpenTl.Schema.Account.IPasswordInputSettings.EmailAsBinary*
  commentId: Overload:OpenTl.Schema.Account.IPasswordInputSettings.EmailAsBinary
  isExternal: false
  name: EmailAsBinary
  nameWithType: IPasswordInputSettings.EmailAsBinary
  fullName: OpenTl.Schema.Account.IPasswordInputSettings.EmailAsBinary
- uid: OpenTl.Schema.Account.IPasswordInputSettings.Email*
  commentId: Overload:OpenTl.Schema.Account.IPasswordInputSettings.Email
  isExternal: false
  name: Email
  nameWithType: IPasswordInputSettings.Email
  fullName: OpenTl.Schema.Account.IPasswordInputSettings.Email
