### YamlMime:ManagedReference
items:
- uid: OpenTl.Schema.TUpdateConfig
  commentId: T:OpenTl.Schema.TUpdateConfig
  id: TUpdateConfig
  parent: OpenTl.Schema
  children: []
  langs:
  - csharp
  - vb
  name: TUpdateConfig
  nameWithType: TUpdateConfig
  fullName: OpenTl.Schema.TUpdateConfig
  type: Class
  source:
    remote:
      path: src/OpenTl.Schema/_generated/_Entities/Update/TUpdateConfig.cs
      branch: master
      repo: https://github.com/OpenTl/OpenTl.Schema.git
    id: TUpdateConfig
    path: ../src/OpenTl.Schema/_generated/_Entities/Update/TUpdateConfig.cs
    startLine: 11
  assemblies:
  - OpenTl.Schema
  namespace: OpenTl.Schema
  syntax:
    content: 'public class TUpdateConfig : object, IUpdate, IObject'
    content.vb: >-
      Public Class TUpdateConfig

          Inherits Object

          Implements IUpdate, IObject
  inheritance:
  - System.Object
  implements:
  - OpenTl.Schema.IUpdate
  - OpenTl.Schema.IObject
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
references:
- uid: OpenTl.Schema
  commentId: N:OpenTl.Schema
  isExternal: false
  name: OpenTl.Schema
  nameWithType: OpenTl.Schema
  fullName: OpenTl.Schema
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: OpenTl.Schema.IUpdate
  commentId: T:OpenTl.Schema.IUpdate
  parent: OpenTl.Schema
  isExternal: false
  name: IUpdate
  nameWithType: IUpdate
  fullName: OpenTl.Schema.IUpdate
- uid: OpenTl.Schema.IObject
  commentId: T:OpenTl.Schema.IObject
  parent: OpenTl.Schema
  isExternal: false
  name: IObject
  nameWithType: IObject
  fullName: OpenTl.Schema.IObject
